version: 2
updates:
  # Python packages
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - janrito
      - risktoparkrageram
