# Generated by Django 3.2.18 on 2023-04-06 13:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_pg_simple_hll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("user_int", models.IntegerField(editable=False)),
                ("user_str", models.TextField(editable=False)),
                ("created", models.DateTimeField()),
            ],
        ),
    ]
