name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: "CI | python v${{ matrix.python-version }}, postgres v${{ matrix.postgres-version }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        postgres-version: ["12", "13", "14"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip setuptools poetry
          poetry install --with dev

      - name: Run Tests
        env:
          POSTGRES_VERSION: ${{ matrix.postgres-version }}
          PYTHON_IMAGE_TAG: "${{ matrix.python-version }}-slim"
        run: poetry run ./run-tests.sh
